/**
 * Created by glenn on 7/31/17.
 */

export const AuthenticationAction = {
  INIT: 'ACTION.AUTHENTICATION.INIT',
  LOGIN_BEGIN: 'ACTION.AUTHENTICATION.LOGIN.BEGIN',
  LOGIN_COMPLETE: 'ACTION.AUTHENTICATION.LOGIN.COMPLETE',
  LOGOUT_BEGIN: 'ACTION.AUTHENTICATION.LOGOUT.BEGIN',
  LOGOUT_COMPLETE: 'ACTION.AUTHENTICATION.LOGOUT.COMPLETE',
  CHANGE_PASSWORD_BEGIN: 'ACTION.AUTHENTICATION.CHANGE_PASSWORD_BEGIN.BEGIN',
  CHANGE_PASSWORD_COMPLETE: 'ACTION.AUTHENTICATION.CHANGE_PASSWORD_BEGIN.COMPLETE',
};
