export const ContactsAction = {

    FETCH_CONTACTS_BEGIN: 'FETCH_CONTACTS_BEGIN',
    FETCH_CONTACTS_SUCCESS: 'FETCH_CONTACTS_SUCCESS',
    FETCH_CONTACTS_ERROR: 'FETCH_CONTACTS_ERROR',
    RESET: 'RESET_CONTACTS_DATA'

};
