export const DocumentsAction = {

    UPDATE_DOCUMENTLIST: 'UPDATE_DOCUMENT_LIST',
    UPDATE_DOCUMENT: 'UPDATE_DOCUMENTS_DATA',
    UPDATE_YEARLIST: 'UPDATE_YEAR_LIST',
    RESET: 'RESET_DOCUMENTS_DATA'

}
