export const ApprovalsAction = {
  FETCH_APPROVALS_BEGIN: 'FETCH_APPROVALS_BEGIN',
  FETCH_APPROVALS_SUCCESS: 'FETCH_APPROVALS_SUCCESS',
  FETCH_APPROVALS_ERROR: 'FETCH_APPROVALS_ERROR',

  RESET: 'RESET_APPROVALS_DATA'
};
