export const MedicalInfoAction = {

    FETCH_PROVIDERS_LOADING: 'FETCH_PROVIDERS_LOADING',
    FETCH_PROVIDERS_SUCCESS: 'FETCH_PROVIDERS_SUCCESS',
    FETCH_PROVIDERS_ERROR: 'FETCH_PROVIDERS_ERROR',
    RESET: 'RESET_PROVIDERS_DATA'

}
